### ISSUE TITLE
skrollr-menu not working on mobile

### ISSUE THREAD

**Issue by benklinger** [Prinzhorn/skrollr-menu#63]
I'm using skrollr-menu at http://ayakorem.co.il/carousel/

The scrolling to hash sections works on desktop but not on mobile. It is not clickable at all.
I read the documentation and saw that it is a common problem, but couldn't find out what i'm doing wrong.

Any help would be appreciated.

**Comment by Prinzhorn** [comment]
You're not using skrollr-menu. This script catches the click before it event reaches skrollr-menu http://ayakorem.co.il/carousel/js/grayscale.js

Is uses 

```
$('html, body').stop().animate({
    scrollTop: $($anchor.attr('href')).offset().top
}, 2500, 'easeInOutExpo');
```

which won't work with skrollr on mobile. You need to use skrollr's `animateTo`
