### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by blackmonday** [Prinzhorn/skrollr-menu#67]
Implemented as detailed and doesn't work. Downloaded source and that doesn't work either. What is the secret to get this working that is missing from GitHub?

**Comment by Prinzhorn** [comment]
Upload a demo. I can't magically know what you've done wrong.

**Comment by blackmonday** [comment]
I¹m not sure how it is working but after following the tutorial on
ihatetomatoes.com I now have it working.

(\ (\
( - -)
((') (')


From:  Alexander Prinzhorn <notifications@github.com>
Reply-To:  Prinzhorn/skrollr-menu
<reply+001ac6519555ed4efb5cac46fd27e6033c0c13e4902424a992cf0000000110e8e0b79
2a169ce0353c0c5@reply.github.com>
Date:  Tuesday, 3 February 2015 19:17
To:  Prinzhorn/skrollr-menu <skrollr-menu@noreply.github.com>
Cc:  Larry Miles <lmiles@lundinoir.com>
Subject:  Re: [skrollr-menu] Doesn't work (#67)


Upload a demo. I can't magically know what you've done wrong.

‹
Reply to this email directly or view it on GitHub
<https://github.com/Prinzhorn/skrollr-menu/issues/67#issuecomment-72715074>
.
