### ISSUE TITLE
Hash URLs not loading properly on page load

### ISSUE THREAD

**Issue by yaronguez** [Prinzhorn/skrollr-menu#69]
Hi, I know there are several other issues posted that are related to this but none seem to reflect the behavior I'm seeing.  

Navigate to:
https://crypteron.com/cipherdb#plans

It takes you to a position on the page significantly above the actual anchor link.  If you click on "Plans" in the sub menu you can see the actual location.  I have a lot of different CSS and scroll animations going off that might be a factor but I'd really like to get some type of work around in place so I can link to this specific position.  Any help is incredibly appreciative, thanks!!

**Comment by Prinzhorn** [comment]
Try initializing skrollr-menu later. It's very obvious that this is caused by stuff that hasn't been loaded (such as images) and later pushes the plans section down (after we already did the jump). In Firefox it even stopped happening with a warm cache.

**Comment by yaronguez** [comment]
Thanks for the tip. I experimented a bit and was able to get it working
properly by placing the skrollr menu init at the very bottom of my
JavaScript files and also setting a 3 second delay.  It's not the greatest
user experience but it's better than nothing.

------------------------------------------------
Yaron Guez
Software Architect / Developer
(781) 767-7434
