### ISSUE TITLE
apply to specific selector option, or add data-attr to disable specific links

### ISSUE THREAD

**Issue by block-head** [Prinzhorn/skrollr-menu#7]
Currently, this plugin adds it's functionality to every single hash link in the document.

Hash links aren't always used to jump to a section. In my case, I'm using fancybox which looks for #element_id in a link's href to open that element_id in a modal.

Would be nice to have an option that will only apply skrollr-menu event to a specific selector.
Alternately, could use data-attr to manually prevent certain elements from receiving event.
Alternately, could use data-attr to manually specify which elements will receive event.

**Comment by yaronguez** [comment]
I'd like to echo this sentiment.  There are some anchor tags I don't want this to effect.  Using event.preventDefault() doesn't seem to help.  Any idea how to make this happen?

**Comment by yaronguez** [comment]
I made a pull request for this here: https://github.com/Prinzhorn/skrollr-menu/pull/64

**Comment by Prinzhorn** [comment]
> Using event.preventDefault() doesn't seem to help.

Because you don't want to prevent the default but prevent the event from bubbling to skrollr-menu. Use `event.stopPropagation()`

**Comment by yaronguez** [comment]
Good to know, thanks for the fast reply!  I still prefer to use the data-ignore-skrollr attribute.  It was only one line of code change.
