### ISSUE TITLE
Add bower.json manifest file

### ISSUE THREAD

**Issue by piotrkulpinski** [Prinzhorn/skrollr-menu#70]
Is there any chance that you could add a bower.json manifest file to skrollr-menu repository?
Just like this one here: https://github.com/Prinzhorn/skrollr/blob/master/bower.json

The most important thing is "main" property because it's required to work with rails assets.
Let me know, thanks

**Comment by Prinzhorn** [comment]
I didn't even know/remeber there was a bower.json in skrollr
