### ISSUE TITLE
Wrong version of Minified library in release 1.0.1 

### ISSUE THREAD

**Issue by ldiaz** [Prinzhorn/skrollr-menu#72]
Hi, have a nice day. Thanks for all your efforts. Just want to report that in the latest release version skrollr-menu 1.0.1, the minified version of the library it's the version from skrollr-menu 1.0.0. In that version isn't working the "data-menu-ignore" logic.

I verified from the github release tab and downloaded the code in .zip and .tar.gz to check. Also bower gets this package.

**Comment by Prinzhorn** [comment]
thanks
