### ISSUE TITLE
/dist/ contains wrong files

### ISSUE THREAD

**Issue by wengenroad** [Prinzhorn/skrollr-menu#82]
Download is:
skrollr-menu-master/dist/skrollr.menu.min.js

missing:
skrollr-menu-master/dist/skrollr.min.js

take this:
https://raw.githubusercontent.com/Prinzhorn/skrollr/master/dist/skrollr.min.js

**Comment by Prinzhorn** [comment]
Skrollr sources are in the skrollr repo and don't belong in this one
